# Generated by Django 5.1.3 on 2025-03-04 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StreamingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_id', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField()),
                ('service_name', models.CharField(max_length=100)),
                ('stream_duration', models.PositiveIntegerField(help_text='Stream duration in seconds')),
                ('playback_type', models.CharField(choices=[('interactive', 'Interactive'), ('non-interactive', 'Non-Interactive')], max_length=20)),
            ],
            options={
                'verbose_name': 'Streaming Record',
                'verbose_name_plural': 'Streaming Records',
                'db_table': 'streaming_record',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['artist_id'], name='streaming_r_artist__47963a_idx'), models.Index(fields=['timestamp'], name='streaming_r_timesta_d58dcc_idx')],
            },
        ),
    ]
